### ISSUE TITLE
Error when trying to run the application

### ISSUE THREAD

**Issue by codingsett** [Mirimon/KivyXamarinReactComparison#1]
Hello i have tried to run the app but i get this error and cannot find a solution for it please assist thanks.

`Traceback (most recent call last):
  File "C:/Users/Kush/Downloads/KivyXamarinReactComparison-master/KivyXamarinReactComparison-master/Kivy/main.py", line 64, in main
    app.run()
  File "C:\Python36\lib\site-packages\kivy\app.py", line 800, in run
    root = self.build()
  File "C:\Users\Kush\Downloads\KivyXamarinReactComparison-master\KivyXamarinReactComparison-master\Kivy\todolist.py", line 31, in build
    self.loadAllKvFiles(os.path.join(self.directory, 'libs', 'uix', 'kv'))
  File "C:\Users\Kush\Downloads\KivyXamarinReactComparison-master\KivyXamarinReactComparison-master\Kivy\todolist.py", line 45, in loadAllKvFiles
    Builder.load_file(kv_file)
  File "C:\Python36\lib\site-packages\kivy\lang\builder.py", line 290, in load_file
    data = fd.read()
  File "C:\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1008: character maps to <undefined>
`

**Comment by HeaTTheatR** [comment]
@codingsett, try this:

```python
    def loadAllKvFiles(self, directory_kv_files):
        from kivy.logger import PY2

        for kv_file in os.listdir(directory_kv_files):
            kv_file = os.path.join(directory_kv_files, kv_file)
            if os.path.isfile(kv_file):
                if PY2:
                    Builder.load_file(kv_file)
                else:
                    with open(kv_file, encoding="utf-8") as kv:
                        Builder.load_string(kv.read())
```

**Comment by codingsett** [comment]
Applied the changes and the app loaded but when i tried to a add a note i got this.


`Traceback (most recent call last):
  File "C:/Users/Kush/Downloads/KivyXamarinReactComparison-master/KivyXamarinReactComparison-master/Kivy/main.py", line 64, in main
    app.run()
  File "C:\Python36\lib\site-packages\kivy\app.py", line 826, in run
    runTouchApp()
  File "C:\Python36\lib\site-packages\kivy\base.py", line 502, in runTouchApp
    EventLoop.window.mainloop()
  File "C:\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 727, in mainloop
    self._mainloop()
  File "C:\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 460, in _mainloop
    EventLoop.idle()
  File "C:\Python36\lib\site-packages\kivy\base.py", line 340, in idle
    self.dispatch_input()
  File "C:\Python36\lib\site-packages\kivy\base.py", line 325, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python36\lib\site-packages\kivy\base.py", line 291, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "C:\Users\Kush\Downloads\KivyXamarinReactComparison-master\KivyXamarinReactComparison-master\Kivy\libs/applibs\kivymd\ripplebehavior.py", line 68, in on_touch_up
    return super(CommonRipple, self).on_touch_up(touch)
  File "C:\Users\Kush\Downloads\KivyXamarinReactComparison-master\KivyXamarinReactComparison-master\Kivy\libs/applibs\kivymd\button.py", line 206, in on_touch_up
    return super(BaseButton, self).on_touch_up(touch)
  File "C:\Python36\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
  File "<string>", line 14, in <lambda>
  File "C:\Users\Kush\Downloads\KivyXamarinReactComparison-master\KivyXamarinReactComparison-master\Kivy\libs\uix\baseclass\ListProjectsActivity.py", line 32, in showDialogCreateProject
    eventsCallback=self.createNewProject).show()
  File "C:\Users\Kush\Downloads\KivyXamarinReactComparison-master\KivyXamarinReactComparison-master\Kivy\libs\applibs\inputdialog\InputDialog.py", line 54, in __init__
    super(InputDialog, self).__init__(**kwargs)
  File "C:\Python36\lib\site-packages\kivy\uix\modalview.py", line 152, in __init__
    super(ModalView, self).__init__(**kwargs)
  File "C:\Python36\lib\site-packages\kivy\uix\anchorlayout.py", line 68, in __init__
    super(AnchorLayout, self).__init__(**kwargs)
  File "C:\Python36\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
    super(Layout, self).__init__(**kwargs)
  File "C:\Python36\lib\site-packages\kivy\uix\widget.py", line 340, in __init__
    super(Widget, self).__init__(**kwargs)
  File "kivy\_event.pyx", line 243, in kivy._event.EventDispatcher.__init__
TypeError: object.__init__() takes no parameters`

**Comment by HeaTTheatR** [comment]
@codingsett - https://github.com/Mirimon/KivyXamarinReactComparison/commit/221cb57841e6f4ffeafc94a3b1731b3ec2cb28d8, https://github.com/Mirimon/KivyXamarinReactComparison/commit/c611bd4dda277e5d8a7aa8c6dc0d88234c086eba

**Comment by codingsett** [comment]
Thanks worked well now
